[package]
org = "xlibb"
name = "pipe"
version = "1.6.1"
authors = ["xlibb"]
keywords = ["pipe"]
repository = "https://github.com/xlibb/module-pipe"
license = ["Apache-2.0"]
distribution = "2201.11.0"
icon = "icon.png"

[[platform.java21.dependency]]
groupId = "io.xlibb.pipe"
artifactId = "pipe-native"
version = "1.6.1"
path = "../native/build/libs/pipe-native-1.6.1.jar"
